name: Dependency Update and Compatibility Test

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Dependencies for Script
      run: pip install packaging requests

    - name: Run Dependency Update Test
      run: python dependency_update_test.py ${{ matrix.python-version }}

    - name: Commit Updated Requirements
      if: ${{ github.event_name == 'workflow_dispatch' && success() }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt with supported Python versions"
        git push
